export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_REGISTER_REQUEST = 'AUTH_REGISTER_REQUEST';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE';
export const AUTH_SET_USER = 'AUTH_SET_USER';
export const AUTH_LOAD_PROFILE = 'AUTH_LOAD_PROFILE';

export const PRODUCTS_FETCH_REQUEST = 'PRODUCTS_FETCH_REQUEST';
export const PRODUCTS_FETCH_SUCCESS = 'PRODUCTS_FETCH_SUCCESS';
export const PRODUCTS_FETCH_FAILURE = 'PRODUCTS_FETCH_FAILURE';
export const PRODUCT_FETCH_REQUEST = 'PRODUCT_FETCH_REQUEST';
export const PRODUCT_FETCH_SUCCESS = 'PRODUCT_FETCH_SUCCESS';
export const PRODUCT_FETCH_FAILURE = 'PRODUCT_FETCH_FAILURE';

export const CART_FETCH_REQUEST = 'CART_FETCH_REQUEST';
export const CART_FETCH_SUCCESS = 'CART_FETCH_SUCCESS';
export const CART_FETCH_FAILURE = 'CART_FETCH_FAILURE';
export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_UPDATE_ITEM = 'CART_UPDATE_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_CLEAR = 'CART_CLEAR';

export const ORDERS_FETCH_REQUEST = 'ORDERS_FETCH_REQUEST';
export const ORDERS_FETCH_SUCCESS = 'ORDERS_FETCH_SUCCESS';
export const ORDERS_FETCH_FAILURE = 'ORDERS_FETCH_FAILURE';
export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAILURE = 'ORDER_CREATE_FAILURE';

export const VENDOR_FETCH_REQUEST = 'VENDOR_FETCH_REQUEST';
export const VENDOR_FETCH_SUCCESS = 'VENDOR_FETCH_SUCCESS';
export const VENDOR_FETCH_FAILURE = 'VENDOR_FETCH_FAILURE';
export const VENDOR_PRODUCTS_FETCH_REQUEST = 'VENDOR_PRODUCTS_FETCH_REQUEST';
export const VENDOR_PRODUCTS_FETCH_SUCCESS = 'VENDOR_PRODUCTS_FETCH_SUCCESS';
export const VENDOR_PRODUCTS_FETCH_FAILURE = 'VENDOR_PRODUCTS_FETCH_FAILURE';
export const VENDOR_PRODUCT_CREATE = 'VENDOR_PRODUCT_CREATE';
export const VENDOR_PRODUCT_UPDATE = 'VENDOR_PRODUCT_UPDATE';
export const VENDOR_PRODUCT_DELETE = 'VENDOR_PRODUCT_DELETE';

export const CATEGORIES_FETCH_REQUEST = 'CATEGORIES_FETCH_REQUEST';
export const CATEGORIES_FETCH_SUCCESS = 'CATEGORIES_FETCH_SUCCESS';
export const CATEGORIES_FETCH_FAILURE = 'CATEGORIES_FETCH_FAILURE';

export const VENDORS_FETCH_REQUEST = 'VENDORS_FETCH_REQUEST';
export const VENDORS_FETCH_SUCCESS = 'VENDORS_FETCH_SUCCESS';
export const VENDORS_FETCH_FAILURE = 'VENDORS_FETCH_FAILURE';
